spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: local
  web:
    resources:
      static-locations: classpath:/static/, file:resources/uploads/
      chain:
        cache: false
  datasource:
    url: jdbc:h2:file:./data/testdb   # jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

jwt:
  secret:
  expiration:

kakao:
  client-id:
  client-secret:
  redirect-uri: http://localhost:3000/

file:
  upload-dir: image
  base-url: http://localhost:8080/images
  s3-bucket: your-s3-bucket-name
  s3-base-url: https://your-s3-bucket-name.s3.amazonaws.com