spring:
  profiles:
    active: local
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:h2:file:./data/testdb   # jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

file:
  upload-dir: src/main/resources/static/uploads
  base-url: http://localhost:8080/static/uploads
  s3-bucket: your-s3-bucket-name
  s3-base-url: https://your-s3-bucket-name.s3.amazonaws.com
