spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: classpath:/static/, file:resources/uploads/
      chain:
        cache: false
  datasource:
    url: jdbc:h2:file:./data/testdb   # jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: 110.8.21.243:9092
    listener:
      missing-topics-fatal: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        max.block.ms: 500
        request.timeout.ms: 300
        delivery.timeout.ms: 3000
        enable.idempotence: true
        reetries: 3
        retry.backoff.ms: 100
        linger.ms: 5
  data:
    redis:
      host: localhost
      port:
      timeout: 300ms


management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      region: seoul   


server:
  forward-headers-strategy: native

jwt:
  secret:
  expiration: 86400000


kakao:
  client-id:
  client-secret:
  redirect-uri: http://localhost:3000/

file:
  upload-dir: images
  base-url: https://backend.owl-dev.me/images
  s3-bucket: your-s3-bucket-name
  s3-base-url: https://your-s3-bucket-name.s3.amazonaws.com
  storage:
    type: local


springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
